FROM mcr.microsoft.com/playwright/python:v1.55.0-noble

COPY . /app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-", "server:app"]