"use client";

import type React from "react";

import { useEffect, useState } from "react";
import { AppLayout } from "../../../components/app-layout";
import { Button } from "../../../components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../../../components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../../../components/ui/tabs";
import { Badge } from "../../../components/ui/badge";
import { Checkbox } from "../../../components/ui/checkbox";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "../../../components/ui/dropdown-menu";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  Clock,
  Users,
  Target,
  Trash2,
  MoreVertical,
  Copy,
  Play,
  FileText,
  GitCompare,
} from "lucide-react";
import { testStore, type Test } from "../../../lib/test-store";
import { supabase } from "../../../lib/supabase";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "../../../components/ui/alert-dialog";
import { useToast } from "../../../hooks/use-toast";

export default function TestsPage() {
  const [tests, setTests] = useState<Test[]>([]);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [testToDelete, setTestToDelete] = useState<string | null>(null);
  const [runCounts, setRunCounts] = useState<Record<string, number>>({});
  const [selectedTests, setSelectedTests] = useState<Set<string>>(new Set());
  const [isSelectionMode, setIsSelectionMode] = useState(false);
  const router = useRouter();
  const { toast } = useToast();

  useEffect(() => {
    const loadTests = async () => {
      const currentTests = await testStore.getTests();
      setTests(currentTests);

      // Load run counts for all tests
      if (currentTests.length > 0) {
        const testIds = currentTests.map((t) => t.id);
        const { data: runData } = await supabase
          .from("test_runs")
          .select("test_id")
          .in("test_id", testIds);

        // Count runs per test
        const counts: Record<string, number> = {};
        runData?.forEach((run: { test_id: string }) => {
          counts[run.test_id] = (counts[run.test_id] || 0) + 1;
        });
        setRunCounts(counts);
      }
    };
    loadTests();

    const interval = setInterval(async () => {
      const currentTests = await testStore.getTests();
      setTests(currentTests);

      // Update run counts
      if (currentTests.length > 0) {
        const testIds = currentTests.map((t) => t.id);
        const { data: runData } = await supabase
          .from("test_runs")
          .select("test_id")
          .in("test_id", testIds);

        const counts: Record<string, number> = {};
        runData?.forEach((run: { test_id: string }) => {
          counts[run.test_id] = (counts[run.test_id] || 0) + 1;
        });
        setRunCounts(counts);
      }
    }, 5000); // Poll every 5 seconds instead of 1 second

    return () => clearInterval(interval);
  }, []);

  const handleDeleteClick = (e: React.MouseEvent, testId: string) => {
    e.preventDefault();
    e.stopPropagation();
    setTestToDelete(testId);
    setDeleteDialogOpen(true);
  };

  const confirmDelete = async () => {
    if (testToDelete) {
      try {
        console.log("Attempting to delete test:", testToDelete);
        const deleted = await testStore.deleteTest(testToDelete);
        console.log("Delete result:", deleted);
        if (deleted) {
          const currentTests = await testStore.getTests();
          setTests(currentTests);
          toast({
            title: "Test deleted",
            description: "The test has been successfully deleted.",
          });
        } else {
          console.error("Delete returned false - check console for details");
          toast({
            title: "Error",
            description: "Failed to delete the test. Check the browser console for details.",
            variant: "destructive",
          });
        }
      } catch (error) {
        console.error("Error deleting test:", error);
        toast({
          title: "Error",
          description: `An error occurred while deleting the test: ${error instanceof Error ? error.message : "Unknown error"}`,
          variant: "destructive",
        });
      }
      setTestToDelete(null);
    }
    setDeleteDialogOpen(false);
  };

  const handleDuplicate = async (test: Test) => {
    try {
      // Preserve all test data including testData and heuristics
      const duplicatedTest: Test = {
        ...test,
        id: "", // New ID will be generated by Supabase
        title: `${test.title} (Copy)`,
        status: "draft" as const,
        lastRun: "Never",
        createdAt: Date.now(),
        // Clear run-specific data
        successRate: undefined,
        avgTime: undefined,
        duration: undefined,
        actionCount: undefined,
        completedAt: undefined,
        feedback: undefined,
        findings: undefined,
        nextSteps: undefined,
        progressState: undefined,
        // Preserve testData and heuristics (spread operator handles this)
      };

      const savedTest = await testStore.saveTest(duplicatedTest);
      if (savedTest) {
        const currentTests = await testStore.getTests();
        setTests(currentTests);
        toast({
          title: "Test duplicated",
          description: `${savedTest.title} has been created as a draft.`,
        });
      } else {
        toast({
          title: "Error",
          description: "Failed to duplicate the test. Please try again.",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Error duplicating test:", error);
      toast({
        title: "Error",
        description: "An error occurred while duplicating the test.",
        variant: "destructive",
      });
    }
  };

  const handleRerun = (test: Test) => {
    // Navigate to the test run page to start a new run
    router.push(`/dashboard/runs/${test.id}`);
  };

  const calculateSuccessRate = (test: Test): number => {
    if (test.status === "running" && test.progressState) {
      return Math.round(
        (test.progressState.completedPersonas / test.progressState.totalPersonas) * 100
      );
    }
    return test.successRate || 0;
  };

  const formatTimeAgo = (timestamp: number): string => {
    const now = Date.now();
    const diff = now - timestamp;
    const minutes = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);

    if (minutes < 1) return "Just now";
    if (minutes < 60) return `${minutes}m ago`;
    if (hours < 24) return `${hours}h ago`;
    return `${days}d ago`;
  };

  const formatDuration = (ms: number): string => {
    const totalSeconds = Math.floor(ms / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${seconds.toString().padStart(2, "0")}`;
  };

  const getTestLink = (test: Test): string => {
    if (test.status === "completed") {
      return `/dashboard/reports/${test.id}`;
    }
    if (test.status === "draft") {
      return `/dashboard/tests/new?id=${test.id}`;
    }
    return `/dashboard/runs/${test.id}`;
  };

  const handleTestSelect = (testId: string, checked: boolean) => {
    setSelectedTests((prev) => {
      const next = new Set(prev);
      if (checked) {
        next.add(testId);
      } else {
        next.delete(testId);
      }
      return next;
    });
  };

  const handleCompare = () => {
    if (selectedTests.size >= 2) {
      const testIds = Array.from(selectedTests);
      const queryParams = testIds.map((id, idx) => `test${idx + 1}=${id}`).join("&");
      router.push(`/dashboard/tests/compare?${queryParams}`);
    } else {
      toast({
        title: "Select tests",
        description: "Please select at least 2 tests to compare.",
        variant: "destructive",
      });
    }
  };

  const toggleSelectionMode = () => {
    setIsSelectionMode(!isSelectionMode);
    if (isSelectionMode) {
      setSelectedTests(new Set());
    }
  };

  const TestCard = ({ test }: { test: Test }) => (
    <div className={`relative group ${isSelectionMode ? "flex items-center gap-4" : ""}`}>
      {isSelectionMode && (
        <div className="flex items-center justify-center shrink-0">
          <Checkbox
            checked={selectedTests.has(test.id)}
            onCheckedChange={(checked) => handleTestSelect(test.id, checked === true)}
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
      <Card
        className={`hover:border-primary transition-colors ${isSelectionMode ? "flex-1" : "w-full"}`}
      >
        <Link
          href={getTestLink(test)}
          className="block"
          onClick={(e) => {
            if (isSelectionMode) {
              e.preventDefault();
              handleTestSelect(test.id, !selectedTests.has(test.id));
            }
          }}
        >
          <CardHeader>
            <div className="flex items-center justify-between">
              <div className="space-y-1 flex-1">
                <CardTitle className="text-xl">{test.title}</CardTitle>
                <CardDescription className="flex items-center gap-4 mt-2">
                  <span className="flex items-center gap-1.5">
                    <Clock className="h-4 w-4" />
                    {test.completedAt ? formatTimeAgo(test.completedAt) : test.lastRun}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <Users className="h-4 w-4" />
                    {test.personas.length} variants
                  </span>
                  <span className="flex items-center gap-1.5">
                    <Target className="h-4 w-4" />
                    {test.artifactType}
                  </span>
                  {runCounts[test.id] !== undefined && runCounts[test.id] > 0 && (
                    <span className="flex items-center gap-1.5">
                      <FileText className="h-4 w-4" />
                      {runCounts[test.id]} result{runCounts[test.id] !== 1 ? "s" : ""}
                    </span>
                  )}
                </CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <Badge
                  variant={test.status === "completed" ? "default" : "secondary"}
                  className="capitalize"
                >
                  {test.status}
                </Badge>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      size="icon"
                      variant="ghost"
                      className="h-8 w-8"
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                      }}
                      aria-label="Test options"
                    >
                      <MoreVertical className="h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        handleRerun(test);
                      }}
                    >
                      <Play className="h-4 w-4 mr-2" />
                      Rerun
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        handleDuplicate(test);
                      }}
                    >
                      <Copy className="h-4 w-4 mr-2" />
                      Duplicate
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      variant="destructive"
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        handleDeleteClick(e, test.id);
                      }}
                    >
                      <Trash2 className="h-4 w-4 mr-2" />
                      Delete
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-6">
              <div>
                <div className="text-2xl font-bold text-foreground">
                  {calculateSuccessRate(test)}%
                </div>
                <div className="text-xs text-muted-foreground">Task success</div>
              </div>
              <div>
                <div className="text-2xl font-bold text-foreground">
                  {test.duration ? formatDuration(test.duration) : test.avgTime || "—"}
                </div>
                <div className="text-xs text-muted-foreground">Avg time</div>
              </div>
              <div className="ml-auto flex flex-wrap gap-2">
                {test.personas.map((persona) => (
                  <Badge key={persona} variant="outline" className="text-xs">
                    {persona}
                  </Badge>
                ))}
              </div>
            </div>
          </CardContent>
        </Link>
      </Card>
    </div>
  );

  return (
    <div className="min-h-screen bg-background">
      <AppLayout>
        <main className="container mx-auto p-6 space-y-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold tracking-tight">Your Tests</h1>
              <p className="text-muted-foreground mt-2">Manage and review your usability tests</p>
            </div>
            <Link href="/dashboard/tests/new">
              <Button size="lg" className="h-11">
                New Test
              </Button>
            </Link>
          </div>

          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Button
                variant={isSelectionMode ? "default" : "outline"}
                size="sm"
                onClick={toggleSelectionMode}
              >
                {isSelectionMode ? "Cancel" : "Select Tests"}
              </Button>
              {isSelectionMode && selectedTests.size >= 2 && (
                <Button size="sm" onClick={handleCompare}>
                  <GitCompare className="h-4 w-4 mr-2" />
                  Compare ({selectedTests.size})
                </Button>
              )}
              {isSelectionMode && selectedTests.size > 0 && (
                <span className="text-sm text-muted-foreground">
                  {selectedTests.size} test{selectedTests.size !== 1 ? "s" : ""} selected
                </span>
              )}
            </div>
          </div>

          <Tabs defaultValue="all" className="space-y-6">
            <TabsList className="bg-muted">
              <TabsTrigger value="all">All</TabsTrigger>
              <TabsTrigger value="drafts">Drafts</TabsTrigger>
              <TabsTrigger value="running">Running</TabsTrigger>
              <TabsTrigger value="completed">Completed</TabsTrigger>
            </TabsList>

            <TabsContent value="all" className="space-y-4">
              {tests.length === 0 ? (
                <Card className="text-center py-12">
                  <CardContent className="space-y-4">
                    <div className="mx-auto w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                      <Target className="h-6 w-6 text-muted-foreground" />
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-lg font-semibold">No tests yet</h3>
                      <p className="text-sm text-muted-foreground max-w-md mx-auto">
                        Create your first test in 2 minutes
                      </p>
                    </div>
                    <Link href="/dashboard/tests/new">
                      <Button size="lg" className="mt-4">
                        New Test
                      </Button>
                    </Link>
                  </CardContent>
                </Card>
              ) : (
                tests.map((test) => <TestCard key={test.id} test={test} />)
              )}
            </TabsContent>

            <TabsContent value="drafts" className="space-y-8">
              {tests.filter((t) => t.status === "draft").length === 0 ? (
                <Card className="text-center py-12">
                  <CardContent className="space-y-4">
                    <div className="mx-auto w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                      <Target className="h-6 w-6 text-muted-foreground" />
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-lg font-semibold">No drafts yet</h3>
                      <p className="text-sm text-muted-foreground max-w-md mx-auto">
                        Create your first test in 2 minutes
                      </p>
                    </div>
                    <Link href="/dashboard/tests/new">
                      <Button size="lg" className="mt-4">
                        New Test
                      </Button>
                    </Link>
                  </CardContent>
                </Card>
              ) : (
                tests
                  .filter((t) => t.status === "draft")
                  .map((test) => <TestCard key={test.id} test={test} />)
              )}
            </TabsContent>

            <TabsContent value="running" className="space-y-8">
              {tests.filter((t) => t.status === "running" || t.status === "queued").length === 0 ? (
                <Card className="text-center py-12">
                  <CardContent className="space-y-4">
                    <div className="mx-auto w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                      <Target className="h-6 w-6 text-muted-foreground" />
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-lg font-semibold">No running tests</h3>
                      <p className="text-sm text-muted-foreground max-w-md mx-auto">
                        Tests will appear here while they&apos;re running
                      </p>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                tests
                  .filter((t) => t.status === "running" || t.status === "queued")
                  .map((test) => <TestCard key={test.id} test={test} />)
              )}
            </TabsContent>

            <TabsContent value="completed" className="space-y-4">
              {tests.filter((t) => t.status === "completed").length === 0 ? (
                <Card className="text-center py-12">
                  <CardContent className="space-y-4">
                    <div className="mx-auto w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                      <Target className="h-6 w-6 text-muted-foreground" />
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-lg font-semibold">No completed tests</h3>
                      <p className="text-sm text-muted-foreground max-w-md mx-auto">
                        Completed tests will appear here
                      </p>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                tests
                  .filter((t) => t.status === "completed")
                  .map((test) => <TestCard key={test.id} test={test} />)
              )}
            </TabsContent>
          </Tabs>

          <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Delete test?</AlertDialogTitle>
                <AlertDialogDescription>
                  This action cannot be undone. This will permanently delete the test and all
                  associated data.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction
                  onClick={confirmDelete}
                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                >
                  Delete
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </main>
      </AppLayout>
    </div>
  );
}
